## Scenario 1: Missing Values

The shipping company has discovered that several passenger records are incomplete. Before
generating reports, management wants to understand the quality of the data.
Tasks:
1. Which columns contain missing information?
2. Which column has the highest number of missing values?
3. Display all passengers whose age is not recorded.
4. Display all passengers whose cabin information is unavailable.
5. If age is mandatory for analysis, how many records would remain after removing missing ages?
6. Suggest a way to retain passengers with missing ages instead of deleting them.

In [18]:
import pandas as pd

df = pd.read_csv('train.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [15]:
df.columns[df.isnull().any()]

Index(['Age', 'Cabin', 'Embarked'], dtype='str')

In [4]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [7]:
df.isnull().sum().idxmin()

'PassengerId'

In [16]:
df[df['Age'].isnull()]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

In [ ]:
df['Age'].isnull().sum()

np.int64(177)

In [12]:
df.isnull().sum()['Cabin']

np.int64(687)

In [14]:
df.shape[0] - df['Age'].isnull().sum()

np.int64(714)

In [17]:
df['Age'] = df['Age'].fillna(df['Age'].median())
df['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888    28.0
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

## Scenario 2: Passenger Demographics

The company wants to understand who traveled on the ship.
Tasks:

1. How many male and female passengers traveled?

2. Which passenger class had the highest number of passengers?

3. What is the average age of passengers in each class?

4. Which class had the oldest passengers on average?

5. Which gender had the youngest average age?

In [20]:
df['Sex'].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [25]:
df['Pclass'].value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [33]:
avg_class = df.groupby('Pclass')['Age'].mean()
avg_class

Pclass
1    38.233441
2    29.877630
3    25.140620
Name: Age, dtype: float64

In [34]:
oldest_class = avg_class.idxmax()
oldest_class

np.int64(1)

In [37]:
avg_gender = df.groupby('Sex')['Age'].mean()
yougest_gender = avg_gender.idxmax()
yougest_gender

'male'

In [39]:
df.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

## Scenario 3: Ticket Revenue Analysis

The finance team wants insights into ticket revenue.
Tasks:

1. What is the total fare collected from all passengers?

2. What is the average fare paid?

3. Which passenger paid the highest fare?

4. Which passenger paid the lowest fare?

5. Which class generated the highest average revenue per passenger?

In [40]:
df['Fare'].sum()

np.float64(28693.9493)

In [41]:
df['Fare'].mean()

np.float64(32.204207968574636)

In [54]:
highest_fare = df.loc[df['Fare'].idxmax()]
highest_fare[['PassengerId','Name','Fare']]

PassengerId                 259
Name           Ward, Miss. Anna
Fare                   512.3292
Name: 258, dtype: object

In [47]:

max_fare = df['Fare'].max()
df[df['Fare']==max_fare]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
258,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C

In [58]:
lowest_fare = df.loc[df['Fare'].idxmin()]
lowest_fare[['PassengerId','Name','Fare']]

PassengerId                    180
Name           Leonard, Mr. Lionel
Fare                           0.0
Name: 179, dtype: object

In [59]:
df.groupby('Pclass')['Fare'].mean()

Pclass
1    84.154687
2    20.662183
3    13.675550
Name: Fare, dtype: float64

## Scenario 4: Survival Investigation

After the disaster, investigators want to identify survival patterns.
Tasks:

1. How many passengers survived?

2. How many passengers did not survive?

3. Which gender had the highest survival count?

4. Which passenger class had the highest survival rate?

5. Did children have a higher survival chance than adults?

In [65]:
df['Survived'].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [64]:
print((df['Survived']==1).sum())

342

In [66]:
print((df['Survived']==0).sum())

549

In [70]:
gender_servived = df.groupby('Sex')['Survived'].sum()
gender_servived

Sex
female    233
male      109
Name: Survived, dtype: int64

In [71]:
gender_servived.idxmax()

'female'

In [76]:
class_servival_rate = df.groupby('Pclass')['Survived'].max()
print(class_servival_rate.idxmax())

1

In [ ]:
df['AgeGroup'] = df['Age'].apply(lambda x: 'childi' f x < 18 else 'Adult')

## Scenario 5: Passenger Name Analysis

The customer service team wants to standardize passenger names.
Tasks:
1. Convert all names to uppercase.
2. Convert all names to lowercase.
3. Find all passengers whose title is "Mr".
4. Find all passengers whose title is "Miss".
5. Replace "Mr." with "Mister".
6. Extract passenger titles into a new column.

## Scenario 6: Family Analysis

The company believes family size influenced survival.
Tasks:
1. Create a new column representing family size.
2. Identify passengers traveling alone.
3. Find passengers traveling with more than three family members.
4. Compare survival rates between solo travelers and family travelers.